// AUTO-GENERATED by scripts/sync-hub.mjs. Do not edit manually.
// This empty snapshot keeps the app runnable before the first Hub sync.
import { BuildingBlockDefinition } from './models';

export const HUB_CATALOG: BuildingBlockDefinition[] = [];
