import { Blueprint, BuildingBlockDefinition, InputBinding } from './models';

function terraformValue(binding: InputBinding, definitions: Map<string, BuildingBlockDefinition>, instanceToDefinition: Map<string, string>): string {
  switch (binding.source) {
    case 'static':
      return JSON.stringify(binding.value ?? '');
    case 'user':
    case 'platform-operator':
      return `var.${binding.value}`;
    case 'meshstack-context':
      return `local.meshstack_context.${binding.contextKey}`;
    case 'bb-output': {
      const sourceDefinitionId = instanceToDefinition.get(binding.sourceBlockId ?? '');
      const sourceDefinition = sourceDefinitionId ? definitions.get(sourceDefinitionId) : undefined;
      const resourceName = (sourceDefinition?.id ?? binding.sourceBlockId ?? 'unknown').replace(/-/g, '_');
      return `meshstack_building_block_v2.${resourceName}.outputs[${JSON.stringify(binding.sourceOutput ?? '')}]`;
    }
  }
}

export function generateTerraform(blueprint: Blueprint, catalog: BuildingBlockDefinition[]): string {
  const definitions = new Map(catalog.map(item => [item.id, item]));
  const instanceToDefinition = new Map(blueprint.blocks.map(block => [block.instanceId, block.definitionId]));
  const blocks = [...blueprint.blocks].sort((a, b) => a.order - b.order);

  const variables = new Map<string, string>();
  for (const block of blocks) {
    const definition = definitions.get(block.definitionId);
    if (!definition) continue;
    for (const input of definition.inputs) {
      const binding = block.inputs[input.name];
      if ((binding?.source === 'user' || binding?.source === 'platform-operator') && binding.value) {
        variables.set(binding.value, input.type);
      }
    }
  }

  const variableCode = [...variables.entries()].map(([name, type]) => `variable ${JSON.stringify(name)} {\n  type = ${type === 'number' ? 'number' : type === 'boolean' ? 'bool' : 'string'}\n}`).join('\n\n');

  const resourceCode = blocks.map(block => {
    const definition = definitions.get(block.definitionId);
    if (!definition) return '';
    const resourceName = definition.id.replace(/-/g, '_');
    const inputLines = definition.inputs.map(input => {
      const binding = block.inputs[input.name];
      if (!binding) return `      # ${input.name} = <unbound>`;
      return `      ${input.name} = ${terraformValue(binding, definitions, instanceToDefinition)}`;
    }).join('\n');

    return `resource "meshstack_building_block_v2" "${resourceName}" {\n  building_block_definition_id = ${JSON.stringify(definition.id)}\n\n  inputs = {\n${inputLines}\n  }\n}`;
  }).filter(Boolean).join('\n\n');

  return `# Generated by meshStack Solution Composer\n# Solution: ${blueprint.name}\n\n${variableCode}${variableCode ? '\n\n' : ''}${resourceCode}\n`;
}
